# .github/workflows/ci-cd.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
        
    - name: Install Dependencies
      run: |
        cd backend && npm install
        cd ../frontend && npm install
        
    - name: Run Tests
      run: |
        cd backend && npm test
        cd ../frontend && npm test
        
    - name: Run Linting
      run: |
        cd backend && npm run lint
        cd ../frontend && npm run lint

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Build and Push Backend
      uses: docker/build-push-action@v2
      with:
        context: ./backend
        file: ./docker/Dockerfile.backend
        push: true
        tags: ghcr.io/${{ github.repository }}/backend:latest
        
    - name: Build and Push Frontend
      uses: docker/build-push-action@v2
      with:
        context: ./frontend
        file: ./docker/Dockerfile.frontend
        push: true
        tags: ghcr.io/${{ github.repository }}/frontend:latest
        
    - name: Deploy to Kubernetes
      uses: steebchen/kubectl@v2
      with:
        config: ${{ secrets.KUBE_CONFIG_DATA }}
        command: apply -f k8s/production/